version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=example
     - POSTGRES_USER=example
     - POSTGRES_DB=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1-fpm-alpine
    restart: always
    ports:
      - "5678:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=localhost:9200
    depends_on:
      - db
  sftp:
    image: "emberstack/sftp:build-5.1.6"
    ports:
      - "22:22"
    volumes:
      - ./sftp-config/config.json:/app/config/sftp.json:ro

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local